### ISSUE TITLE
Issue with CRAFT MODALS:.

### ISSUE THREAD

**Issue by Djive** [thejoshsmith/craft-prism-syntax-highlighting#11]
Thank you for last fix. that resolved preview. issue.. 

But now have issue with Craft modals.. 
![Snag_1b90742](https://user-images.githubusercontent.com/1241189/95456821-3aa7e180-0970-11eb-8074-3a90b9b47702.png)

can you help with that, i checked.. 
and when i turn off prism all works ok..

**Comment by Djive** [comment]
If needed i can donate if you can make this thing working..
As need this plugin on couple projects..

**Comment by moacode** [comment]
Hi @Djive, if you'd like to sponsor this project that would be much appreciated but not necessary. I will have a look at this tonight for you.

**Comment by moacode** [comment]
Hi @Djive, could you please email me your composer json and lock file to [me@joshsmith.dev](mailto:me@joshsmith.dev)? I tried to replicate but it's all working fine for me so I'd like to try and replicate your setup.

**Comment by Djive** [comment]
sent you email with data, thx..

**Comment by Djive** [comment]
Can i send you pull request...

**Comment by moacode** [comment]
Yes please, look forward to it!
