### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by jan-dh** [thejoshsmith/craft-prism-syntax-highlighting#13]
Hi there, just wanted to check if this plugin is still under active development.

**Comment by moacode** [comment]
Hey @jan-dh, yes it is (been very busy lately sorry) and I'm aiming to release version 2 within the next couple of weeks.

**Comment by jan-dh** [comment]
Thanks for the quick reply! Installing right now

**Comment by moacode** [comment]
No problem! If you strike any issues let me know 😄
