### ISSUE TITLE
Cache prevent the plugin to render

### ISSUE THREAD

**Issue by Mamboleoo** [thejoshsmith/craft-prism-syntax-highlighting#16]
I realised that the plugin was loading Prism CSS/JS files randomly.
After some debug I think the issue comes from my content being wrapped inside the {% cache %} tags.
If I disable the cache around my content then the plugin is being executed perfectly on each page reload.
I don't know if the issue is actually from the plugin or from Craft that prevents the plugin to detects if Prism is needed.

**Comment by engram-design** [comment]
This is pretty much down to how CSS/JS works with Craft 3 and the `{% cache %}` tag. There's not a whole lot to do about it, other than not use the tags, or add the JS/CSS outside of the cache tags.

However, this is no longer an issue in Craft 4, and [3.0.0](https://github.com/verbb/prism/releases/tag/3.0.0)
