### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by richhayler** [thejoshsmith/craft-prism-syntax-highlighting#24]
I would love to see this plugin come to Craft 4. Are their any plans to update for Craft 4?

**Comment by engram-design** [comment]
Just to chime in, we've added this to our [Craft 3 migration project](https://verbb.io/craft-3), as people are keen to see this plugin on Craft 4.

If you're no longer developing this plugin, we'd be happy to continue development at Verbb (including updating to Craft 4) - but just let us know if you've got plans to continue things and update to Craft 4! @moacode

**Comment by moacode** [comment]
Hey @engram-design, thanks for this. Unfortunately I'm not really part of the Craft world these days due to do a change in job (😢) - Mainly Laravel, React or blockchain nowadays.

I have good intentions to port it but the reality is that I probably won't get to it any time soon.

If you would like to take it over and continue development then that is absolutely fine by me—Let me know what you need.

Apologies @richhayler for not responding to your comment in a timely manner.

**Comment by engram-design** [comment]
@moacode Completely understand! If you want to transfer this repository to `verbb` or myself `engram-design` (you might have to add me as a collaborator first, then promote to admin), we'd be happy to continue development!

And you would be more than welcome to take this back in the future if you'd like to continue on with this. We're just trying to give people a hand where we can, but not looking to rip plugins away from people forcibly! 🙂

**Comment by engram-design** [comment]
@moacode Just wanted to check in about transferring this repo, so we can kick things off?

**Comment by brechtDR** [comment]
Just wanted to add my vote for a craft 4 upgrade. I really love this plugin. But it holds me back for upgrading. I do understand that you're not really a part of the craft community anymore. But maybe you can find a solution with an extra contributor? Best of luck on your change of job!

**Comment by engram-design** [comment]
Still keen to convert this over, just waiting for @moacode to get back to me about transferring the repository.

Otherwise, might have to fork it and start another repo, it'd just be good to keep the issues and commit history for the plugin.

**Comment by moacode** [comment]
Hey @engram-design, sorry for the delay. I tried to transfer it to Verbb but was unable to. I've added you as a collaborator 😄

**Comment by engram-design** [comment]
@moacode No problem! I've just accepted and I _think_ you can promote me to an admin. Transferring directly to Verbb is only possible if it's from another organisation account I believe, so transferring to me personally should do the tricky. Or inviting me as a collaborator, and promoting to admin.

Sorry for the hassle!

**Comment by engram-design** [comment]
@moacode Just wanted to check if you're able to transfer this repo to `engram-design` and I can take it from here?

**Comment by siffring** [comment]
+1 for getting this upgraded to Craft 4

**Comment by engram-design** [comment]
@moacode Any luck getting me setup as an admin on the repo to kick off the transfer?

**Comment by moacode** [comment]
Hey @engram-design,

I had trouble when I attempted this last, but I just tried again and a request should have gone through to you now 😄

**Comment by engram-design** [comment]
Thanks @moacode that’s sorted it!

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/prism/releases/tag/3.0.0).

Do note however that the plugin has changed to `verbb/prism`.

To migrate, run the following:

```shell
php craft plugin/uninstall craft-prism-syntax-highlighting
composer require verbb/prism && composer remove thejoshsmith/craft-prism-syntax-highlighting
php craft plugin/install prism
```

The new plugin will migrate your fields across.
