### ISSUE TITLE
Code Styling Issue after upgrading to CraftCMS v3.4

### ISSUE THREAD

**Issue by richhayler** [thejoshsmith/craft-prism-syntax-highlighting#3]
<img width="645" alt="Screenshot 2020-01-29 14 31 38" src="https://user-images.githubusercontent.com/2505643/73325826-14d82200-42a4-11ea-8eaf-f81559874c57.png">

Span tags have some default control panel box shadow styling applied to them.

The specific rule is in main.scss:

*:not(.highlight) > * > * > .token 

``-webkit-box-shadow: 0 0 0 1px rgba(123, 135, 147, 0.5);
box-shadow: 0 0 0 1px rgba(123, 135, 147, 0.5);``

I resolved this by adding the following to the prism css:

``.prism-syntax-highlighter .token {box-shadow: none !important;}``

**Comment by moacode** [comment]
Thanks for reporting @richhayler, I'll look into this over the next couple of days!

**Comment by moacode** [comment]
@richhayler this has definitely taken longer to get to than a couple of days 😆. I will look at this one over the weekend—Sorry for the delay!

**Comment by moacode** [comment]
Fixed in release 1.0.2 (https://github.com/thejoshsmith/craft-prism-syntax-highlighting/commit/fb424f0fdcc703d100779c34d320a21d17d122a9)
