### ISSUE TITLE
Pressing "Enter / Return" does not add a new line

### ISSUE THREAD

**Issue by richhayler** [thejoshsmith/craft-prism-syntax-highlighting#7]
In the editor when I press "enter" to add a new line this keystroke saves the entry draft instead.

Craft Version: 3.4.43
Plugin Version: 1.0.2

**Comment by moacode** [comment]
Interesting, I haven't tested with the newer versions of Craft. This shouldn't be too difficult to resolve.

**Comment by richhayler** [comment]
Ah, some more info....

In my specific scenario I have two entry types. The second entry type is the one configured with a prism field. When I create a new entry and then switch to the second entry type this is when I'm encountering the issue. If the field is configured for the first (default) entry type it seems to work as expected. 

I will keep testing to confirm.

**Comment by richhayler** [comment]
Yes, I can confirm the above behaviour is what I'm experiencing.

**Comment by moacode** [comment]
Hi @richhayler, unfortunately I'm not able to replicate this one. I've tried across Chrome/Firefox/Safari and have uploaded a screen recording below. Let me know if I'm missing something!

[prism-return-test.mov.zip](https://github.com/thejoshsmith/craft-prism-syntax-highlighting/files/4764376/prism-return-test.mov.zip)

**Comment by richhayler** [comment]
Thanks for taking a look. I'll disable some plugins and also try to dig a bit deeper to understand what's causing the behaviour. It works fine in every scenario apart from when I switch entry types but as you've shown it might be my specific setup.

**Comment by richhayler** [comment]
Ok, I've tried a bunch of things:

I've narrowed it down to **if I have an asset field after the prism field** this seems to cause the issue. I ruled out it being related to switching the entry type by changing the entry type that contained then prism field to be the default (which still resulted in not being able to create a new line).

Ive attached a screenshot below of what my entry form looks like.

<img width="824" alt="Screen Shot 2020-06-14 at 7 48 31 am" src="https://user-images.githubusercontent.com/2505643/84579773-3fbab100-ae14-11ea-867e-39f3521213ce.png">

**Comment by richhayler** [comment]
If I remove the asset field then I can create a new line in the editor.

**Comment by moacode** [comment]
Thanks @richhayler, I'm currently doing a big upgrade of this plugin and just replicated the same issue.

This is actually caused by Craft loading its own version of the PrismJS library (for previewing asset uploads), which is causing conflicts with the plugin.

My solution is to remove Craft's version from the CP when this plugin is installed, being mindful to load the syntax and theme(s) Craft requires to ensure compatibility. When I first made this plugin Craft wasn't using it's own version of the PrismJS library!

I'll aim to release a patch this evening.

**Comment by richhayler** [comment]
Thanks @thejoshsmith, I'm glad you were able to replicate the issue and work out the cause of the issue. Thanks for keeping this plugin going, it gives me a great deal of flexibility in terms of manipulating content via the control panel.

**Comment by moacode** [comment]
No worries @richhayler. Could you please install version `1.0.4` and let me know if this fixes the issue?

BTW the update I'm working on allows you to render code blocks on the front end using `{{ entry.mySyntaxHighlighterField.render() }}` and also use the plugin within Redactor, so if you're keen to test this out I'll let you know when a beta version is available.
